### ISSUE TITLE
这次更新了之后需要加  0x10是吗

### ISSUE THREAD

**Issue by suyu926** [CalvinXu17/JD_DMA#1]
这次更新了之后需要加  0x10是吗，我加了还是没效果为什么
		GNames = DecryptCall(Read<uint64_t>(GameNULL+Offset::GNames));
		GNames = DecryptCall(Read<uint64_t>(GNames+0x10)); if (ValidPtr(GNames , sizeof(uint64_t)))continue;
是在这添加吗

**Comment by CalvinXu17** [comment]
> 这次更新了之后需要加 0x10是吗，我加了还是没效果为什么 GNames = DecryptCall(Read<uint64_t>(GameNULL+Offset::GNames)); GNames = DecryptCall(Read<uint64_t>(GNames+0x10)); if (ValidPtr(GNames , sizeof(uint64_t)))continue; 是在这添加吗

检查其他偏移

**Comment by suyu926** [comment]
> > 这次更新了之后需要加 0x10是吗，我加了还是没效果为什么 GNames = DecryptCall（Read<uint64_t>（GameNULL+Offset：：GNames））;GNames = DecryptCall（Read<uint64_t>（GNames+0x10））;if （ValidPtr（GNames ， sizeof（uint64_t）））继续;是在这添加吗
> 
> 检查其他偏移

我检查了offset没有错的

**Comment by CalvinXu17** [comment]
> > > 这次更新了之后需要加 0x10是吗，我加了还是没效果为什么 GNames = DecryptCall（Read<uint64_t>（GameNULL+Offset：：GNames））;GNames = DecryptCall（Read<uint64_t>（GNames+0x10））;if （ValidPtr（GNames ， sizeof（uint64_t）））继续;是在这添加吗
> 
> > 
> 
> > 检查其他偏移
> 
> 
> 
> 我检查了offset没有错的

我这里没有任何问题
