### ISSUE TITLE
自瞄疑问

### ISSUE THREAD

**Issue by iddddg** [CalvinXu17/JD_DMA#3]
大佬JD里面自瞄是怎么用，是LogiNet吗？这个是什么软件/设备

**Comment by CalvinXu17** [comment]
> 大佬JD里面自瞄是怎么用，是LogiNet吗？这个是什么软件/设备

我的另一个鼠标宏程序，调用罗技驱动移动鼠标，接收网络命令包

**Comment by iddddg** [comment]
是PUBG-Logitech这个项目里logi.exe中宏配置面板底部的LogiNet对吧。
另外弱弱问下大佬这个JD_DMA能否考虑开放源代码，仅自用保留版权声明，只是想学习下，研究看看能否加上kmbox啥的

**Comment by CalvinXu17** [comment]
> 是PUBG-Logitech这个项目里logi.exe中宏配置面板底部的LogiNet对吧。 另外弱弱问下大佬这个JD_DMA能否考虑开放源代码，仅自用保留版权声明，只是想学习下，研究看看能否加上kmbox啥的

圈太多，暂无开源打算
